name: Website Request
description: Request to add a website to this repository
title: "[Website] I want "
labels: [Request, enhancement, games]

body:
- type: markdown
attributes:
  value: "Thanks for wanting to add games!"

- tpye: input
  id: Name
  attributes:
    label: Name of game
    description: What is the name of the game you would like to add?
    placeholder: ex. Github Issue Forms
    value: "I"
validations:
    required: true


- type: input
  id: info
  attributes:
  label: Website link
  description: What is the link to the website you would like to add?
  placeholder: ex. Github Issue Forms
  validations:
  required: true
