name: Website Request
description: Request to add a website to this repository
title: "[Website] I want "
labels: [Request, enhancement, games]
assingees: 

body:
  - tpye: input
  attributes:
  value: 
    This is the name of the game you would like to add.

  - type: input
  attributes:
  value:
   This is the website the game can be found on.
