name: Website request
description: Request to add a game website
title: "[Tip]: I want "
labels: [game, website, add game]
assignees:
  - zryak
body:
  - type: markdown
    attributes:
      value: |
        Thanks for requesting to add a Game. It should go up shortly
  - type: input
    id: Name
    attributes:
      label: Name of Game
      description: What is the name of Game?
      placeholder: ex. GitHub Issue Forms
    validations:
      required: true
  - type: input
    id: Website
    attributes:
      label: Name of Website
      description: What is the link to this website?
      placeholder: ex. GitHub Issue Forms
    validations:
      required: true
