name: Website Request
description: Request to add a website to this repository
title: "[Website] I want "
labels: [Request, enhancement, games]
assingees: 

body:
This form is to add a website to this repository, please go through each of the steps to add your website. I will try to include the site a soon as possible.

The game I am adding is called
input:
, the website you may access this link is
textarea:
. The category this game belongs in is
input:
